# Generated by Django 5.1.3 on 2024-11-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_phone', models.CharField(max_length=15)),
                ('sender_address', models.CharField(default='Chittagong Road, Narayanganj', max_length=255)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_phone', models.CharField(max_length=15)),
                ('receiver_address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cod_option', models.BooleanField(default=False)),
                ('cod_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cod_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_booked', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Parcel',
        ),
    ]
