# Generated by Django 5.1.3 on 2024-11-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_parcelbooking_remove_parcel_customer_delete_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelbooking',
            name='payment_option',
            field=models.CharField(choices=[('cash', 'Cash'), ('to_pay', 'To Pay')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='parcelbooking',
            name='pickup_system',
            field=models.CharField(choices=[('home_delivery', 'Home Delivery'), ('office_delivery', 'Office Delivery')], default='office_delivery', max_length=15),
        ),
    ]
